"""Build the sealed-reference denylist and audit the corpus against it (2R.2).

The hard constraint is that the organizers' reference subset never influences
any fitting. Enforcing that needs fingerprints of the sealed images, so this
script hashes them through the SAME canonical decode path the pipeline uses
and emits `feature_cache.load_denylist`'s exact format:

    <sha256>  phash=<16 hex>   # one sealed image per line

Hashing is not training. The sealed images are read once, fingerprinted, and
never handed to a model, a threshold, or a split.

It then AUDITS the corpus against the denylist and reports every exact and
perceptual hit, so contamination is a measured number rather than an
assumption.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.pipeline.decode import DecodeError, decode_image

IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp", ".bmp"}


def hamming(a: str, b: str) -> int:
    return (int(a, 16) ^ int(b, 16)).bit_count()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--sealed-dir", type=Path, action="append", required=True,
                    help="directory of sealed reference images (repeatable)")
    ap.add_argument("--label", action="append", default=None,
                    help="human label for each --sealed-dir, in the same order")
    ap.add_argument("--corpus-hashes", type=Path,
                    default=Path("data/manifests/router_corpus_hashes.json"))
    ap.add_argument("--out", type=Path, default=Path("data/manifests/sealed_denylist.txt"))
    ap.add_argument("--audit-out", type=Path,
                    default=Path("results/corpus/sealed_contamination_audit.json"))
    ap.add_argument("--phash-threshold", type=int, default=6,
                    help="Hamming radius counted as a perceptual hit; the default "
                         "matches feature_cache's own sealed-denylist default")
    args = ap.parse_args()

    labels = args.label or [d.name for d in args.sealed_dir]
    if len(labels) != len(args.sealed_dir):
        print("--label must be given once per --sealed-dir", file=sys.stderr)
        return 2

    started = time.perf_counter()
    entries: list[dict] = []
    failures: list[dict] = []
    for label, directory in zip(labels, args.sealed_dir, strict=True):
        files = sorted(p for p in directory.rglob("*") if p.suffix.lower() in IMAGE_SUFFIXES)
        print(f"{label}: {len(files)} images under {directory}", file=sys.stderr)
        for i, path in enumerate(files):
            try:
                decoded = decode_image(path)
            except DecodeError as exc:
                failures.append({"path": str(path), "error": str(exc)})
                continue
            entries.append({"sha256": decoded.sha256, "phash": decoded.phash,
                            "subset": label})
            if (i + 1) % 1000 == 0:
                print(f"  {label} {i + 1}/{len(files)}", file=sys.stderr, flush=True)

    if not entries:
        print("no sealed images hashed; refusing to write an empty denylist", file=sys.stderr)
        return 2

    lines = [
        "# Sealed organizer reference subset — SHA-256 + perceptual hashes.",
        "# NEVER an input to any fitting. Generated by scripts/build_denylist.py.",
        f"# subsets: {', '.join(f'{lb}={sum(1 for e in entries if e['subset'] == lb)}' for lb in labels)}",
    ]
    lines.extend(f"{e['sha256']}  phash={e['phash']}  # {e['subset']}" for e in entries)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")

    # ---- audit the corpus against what we just built -----------------------
    audit: dict = {"schema_version": "sealed-contamination-audit.v1",
                   "denylist": str(args.out), "n_sealed": len(entries),
                   "phash_threshold": args.phash_threshold}
    if args.corpus_hashes.exists():
        corpus = json.loads(args.corpus_hashes.read_text())["hashes"]
        sealed_sha = {e["sha256"] for e in entries}
        exact = [{"source_id": s, "sha256": v["sha256"]}
                 for s, v in corpus.items() if v["sha256"] in sealed_sha]
        # 13.8k x 5k Hamming distances: vectorised byte-XOR + popcount LUT,
        # chunked so the intermediate stays small. Exact, not approximate --
        # a contamination check must not miss a hit to save time.
        popcount = np.array([i.bit_count() for i in range(256)], dtype=np.uint8)

        def to_matrix(hexes):
            return np.stack([np.frombuffer(bytes.fromhex(h), dtype=np.uint8) for h in hexes])

        source_ids = list(corpus)
        corpus_matrix = to_matrix([corpus[s]["phash"] for s in source_ids])
        sealed_matrix = to_matrix([e["phash"] for e in entries])
        perceptual = []
        for start in range(0, len(corpus_matrix), 512):
            block = corpus_matrix[start:start + 512]
            dist = popcount[np.bitwise_xor(block[:, None, :],
                                           sealed_matrix[None, :, :])].sum(axis=2)
            nearest = dist.argmin(axis=1)
            best = dist[np.arange(len(block)), nearest]
            for offset in np.nonzero(best <= args.phash_threshold)[0]:
                sealed = entries[int(nearest[offset])]
                perceptual.append({"source_id": source_ids[start + int(offset)],
                                   "distance": int(best[offset]),
                                   "sealed_subset": sealed["subset"],
                                   "sealed_sha256": sealed["sha256"]})
        audit["min_perceptual_distance_observed"] = int(min(
            popcount[np.bitwise_xor(corpus_matrix[s:s + 512][:, None, :],
                                    sealed_matrix[None, :, :])].sum(axis=2).min()
            for s in range(0, len(corpus_matrix), 512)))
        audit.update({"n_corpus_sources": len(corpus), "n_exact_hits": len(exact),
                      "n_perceptual_hits": len(perceptual),
                      "exact_hits": exact, "perceptual_hits": perceptual,
                      "clean": not exact and not perceptual})
    audit["decode_failures"] = failures
    audit["elapsed_seconds"] = round(time.perf_counter() - started, 1)
    args.audit_out.parent.mkdir(parents=True, exist_ok=True)
    args.audit_out.write_text(json.dumps(audit, indent=2) + "\n")

    print(json.dumps({k: v for k, v in audit.items()
                      if k not in ("exact_hits", "perceptual_hits", "decode_failures")},
                     indent=2), file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
