"""Generate `configs/frozen.yaml` — the frozen reproduction manifest.

B-032 P0: the build plan's exit test is `scripts/run_eval.py --config configs/frozen.yaml`,
and neither the config nor the flag existed. This writes the config from the repository's
current state: for every published table, the artifact, the inputs it was computed from,
their SHA-256s, and the command that regenerates it.

Hashes are recorded, never invented -- run this only when the artifacts are the ones you
intend to publish. `scripts/reproduce_frozen.py` is what CHECKS them.
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# (name, artifact, inputs, command, regenerable)
TABLES = [
    ("internal_test_headline", "results/internal-test/results.json",
     ["data/feature_cache/internal-test-v2/rows.jsonl",
      "results/router-fitting-v2/router_reliability.pt",
      "results/router-fitting-v2/threshold-artifact.v1.json"],
     ("python scripts/evaluate_internal_test.py --cache data/feature_cache/internal-test-v2 "
      "--checkpoint results/router-fitting-v2/router_reliability.pt "
      "--threshold-artifact results/router-fitting-v2/threshold-artifact.v1.json"), True),
    ("ablation_ladder", "results/internal-test/ablation.json",
     ["data/feature_cache/fitting-v2/rows.jsonl",
      "data/feature_cache/internal-test-v2/rows.jsonl"],
     "python scripts/ablation_matrix.py", True),
    ("abstention", "results/internal-test/abstention.json",
     ["data/feature_cache/internal-test-v2/rows.jsonl",
      "results/router-fitting-v2/router_reliability.pt"],
     "python scripts/abstention_report.py", True),
    ("fpr_matched_baseline", "results/internal-test/fpr-matched-baseline.json",
     ["data/feature_cache/internal-test-v2/rows.jsonl"],
     "python scripts/diagnostics/fpr_matched_baseline.py", True),
    ("second_holdout", "results/holdout/validation.json",
     ["data/feature_cache/holdout-v1/rows.jsonl",
      "results/router-fitting-v2/router_reliability.pt"],
     "python scripts/validate_on_holdout.py", True),
    ("retention_certificate", "results/robustness/retention-signal.json",
     ["data/feature_cache/internal-test-v2/rows.jsonl"],
     "python scripts/diagnostics/retention_signal.py", True),
    ("probe_ablation", "results/probe-ablation/dev-results.json",
     ["data/feature_cache/fitting-v2/rows.jsonl"],
     "python scripts/probe_ablation.py", True),
    ("ops_evidence", "results/ops/ops-evidence.json", [],
     "python scripts/measure_ops.py", False),
    ("clean_checkout", "results/clean-checkout/verification.json", [],
     "python scripts/verify_clean_checkout.py", False),
    ("sealed_reference", "results/sealed/reference-results.json",
     ["results/sealed/predictions.jsonl",
      "data/manifests/sealed_files.json",
      "results/router-fitting-v2/threshold-artifact.v1.json"],
     "python scripts/sealed_reference_report.py", True),
]

SEALED = "sealed_reference"


def sha256(path: Path) -> str | None:
    path = ROOT / path
    if not path.exists():
        return None
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    out = ROOT / "configs" / "frozen.yaml"
    lines = [
        "# THE FROZEN REPRODUCTION MANIFEST",
        "#",
        "# The build plan's Phase-4 exit test is:",
        "#     scripts/run_eval.py --config configs/frozen.yaml",
        "# which verifies that every published table still matches the artifact it was",
        "# published from, and that every artifact still matches the inputs it was",
        "# computed from. `--regenerate` re-runs the commands below and reports drift.",
        "#",
        "# Generated by scripts/make_frozen_config.py; CHECKED by",
        "# scripts/reproduce_frozen.py. Hashes are recorded from the artifacts as they",
        "# stand, so regenerate this file only when the artifacts are the ones you mean",
        "# to publish.",
        "#",
        "# THE SEALED ENTRY IS SUMMARY-ONLY. Its command reads the preserved prediction",
        "# dump and never invokes the model: the sealed subset is scored exactly once,",
        "# and it already was. Any tool that would re-run inference on it is a bug.",
        'schema_version: "frozen-reproduction.v1"',
        'expert_revision: "6076002bf0d9dd37537f965ee2f06f826c333b61"',
        "tables:",
    ]
    missing = []
    for name, artifact, inputs, command, regenerable in TABLES:
        a_sha = sha256(Path(artifact))
        if a_sha is None:
            missing.append(artifact)
            continue
        lines.append(f"  - name: {name}")
        lines.append(f"    artifact: {artifact}")
        lines.append(f"    artifact_sha256: {a_sha}")
        lines.append(f"    regenerable: {str(regenerable).lower()}")
        if name == SEALED:
            lines.append("    sealed: true")
            lines.append("    summary_only: true   # reads the preserved dump; never model inference")
        lines.append(f"    command: {command!r}")
        if inputs:
            lines.append("    inputs:")
            for src in inputs:
                s = sha256(Path(src))
                lines.append(f"      - path: {src}")
                lines.append(f"        sha256: {s if s else 'ABSENT'}")
                if s is None:
                    lines.append("        note: git-ignored locally-built input; "
                                 "absence is expected in a clean clone")
        lines.append("")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} with {len(TABLES) - len(missing)} tables")
    if missing:
        print(f"WARNING: {len(missing)} artifact(s) absent and omitted: {missing}",
              file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
